---
- name: Deploy The Monitor Application
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    # Verify Docker is running
    - name: Check if Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    # Create application directory
    - name: Create app directory
      file:
        path: /opt/the-monitor
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user

    # Copy configuration files
    - name: Copy Docker Compose file
      copy:
        src: "../docker-compose.yml"
        dest: "/opt/the-monitor/docker-compose.yml"
        owner: ec2-user
        group: ec2-user

    - name: Copy Caddyfile
      copy:
        src: "../Caddyfile"
        dest: "/opt/the-monitor/Caddyfile"
        owner: ec2-user
        group: ec2-user

    - name: Copy Prometheus config
      copy:
        src: "../prometheus.yml"
        dest: "/opt/the-monitor/prometheus.yml"
        owner: ec2-user
        group: ec2-user

    # Install Docker Compose
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # Start the application with Docker Compose
    - name: Start with Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/the-monitor
        state: present