---
- name: Configure Ubuntu Server for The Monitor
  hosts: all
  become: yes

  tasks:
    # Update packages
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install required packages for Docker
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # Add Docker GPG key
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Add Docker repository
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    # Install Docker & Docker CLI
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    # Install Docker Compose
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # Create app folder
    - name: Create application directory
      file:
        path: /opt/the-monitor
        state: directory
        mode: '0755'

    # Copy config files from repo to server
    - name: Copy Docker Compose file
      copy:
        src: "../docker-compose.yml"
        dest: "/opt/the-monitor/docker-compose.yml"

    - name: Copy Caddyfile
      copy:
        src: "../Caddyfile"
        dest: "/opt/the-monitor/Caddyfile"

    - name: Copy Prometheus config
      copy:
        src: "../prometheus.yml"
        dest: "/opt/the-monitor/prometheus.yml"

    # Start Docker Compose stack
    - name: Start Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: /opt/the-monitor
        state: present

    # Ensure Docker runs on reboot
    - name: Ensure Docker service is enabled
      systemd:
        name: docker
        state: started
        enabled: yes
